
  
--EX.1

CREATE TABLE Salariati_S AS
SELECT 
    ID_ANGAJAT, 
    PRENUME, 
    NUME, 
    DATA_ANGAJARE, 
    ID_FUNCTIE, 
    SALARIUL, 
    ID_MANAGER, 
    ID_DEPARTAMENT
FROM Angajati
WHERE ID_DEPARTAMENT IN (1, 2, 3);  
DESC Departamente;

--EX.2
ALTER TABLE Salariati_S
ADD Prima NUMBER(5, 2) DEFAULT 0.10;
--EX.3
UPDATE Salariati_S
SET Prima = 0.15;

--EX.4
ALTER TABLE Salariati_S
ADD CONSTRAINT pk_id_angajat PRIMARY KEY (ID_ANGAJAT);

--EX.5
ALTER TABLE Salariati_S
MODIFY Prima NUMBER(5, 2) NOT NULL;

--EX.6
ALTER TABLE Salariati_S
MODIFY Prima NUMBER(5, 2) NULL;

--EX.7
ALTER TABLE Salariati_S
DROP COLUMN Prima; 

--EX.8
UPDATE Salariati_S
SET SALARIUL = SALARIUL * 0.90
WHERE DATA_ANGAJARE < '2016-06-01';

--EX.9
UPDATE Salariati_S
SET SALARIUL = SALARIUL * 1.15
WHERE ID_MANAGER IN (120, 121, 122, 123, 124, 125) 
AND ID_FUNCTIE <> 'ST_MAN';

--EX.10
UPDATE Salariati_S
SET SALARIUL = (SELECT MAX(SALARIUL) FROM Angajati),
    ID_FUNCTIE = (SELECT ID_FUNCTIE FROM Angajati WHERE SALARIUL = (SELECT MAX(SALARIUL) FROM Angajati))
WHERE ID_DEPARTAMENT = 50 AND ID_MANAGER = 100;

--EX.11
DELETE FROM Salariati_S
WHERE DATA_ANGAJARE < '2000-01-01' AND SALARIUL IS NULL;



--EX.12
BEGIN TRANSACTION;

DELETE FROM Salariati_S
WHERE DATA_ANGAJARE < ADD_MONTHS(SYSDATE, -36);

ROLLBACK;
